CREATE TABLE IF NOT EXISTS Telemetry (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  company_id INT NULL,
  device_id VARCHAR(128) NULL,
  payload JSON,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
